package by.htp.project1.controller.command;

public enum CommandName {
	
	LOGINATION,REGISTRATION, SAVENEWUSER, GOTOINDEXPAGE, GOTOMAINPAGE, LOGOUT,LOGINATIONPAGE,
	EDIT,READWHOLENEWS,NEWSUPDATE;
}
